server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/testdb
    username: postgresadmin
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
